### ISSUE TITLE
compatibilidade com python3

### ISSUE THREAD

**Issue by aleprovencio** [guicarvalho/correiospy#1]
Blz @guicarvalho ?
Acho que para o correiospy ser compatível com o python3 basta corrigir as chamadas da urllib2 que não funciona mais como no python2.

**Comment by aleprovencio** [comment]
PR https://github.com/guicarvalho/correiospy/pull/2 criado!

**Comment by guicarvalho** [comment]
Boa tarde @aleprovencio PR Aprovado.
